services:
  app:
    build: config/webserver
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./config/webserver:/etc/nginx/sites-available


  mysql:
    build: config/database
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password1
      MYSQL_DATABASE: internship


  phpmyadmin:
    image: phpmyadmin:5.2.1