services:
  app:
    build: config/webserver
    container_name: nginx
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./config/webserver:/etc/nginx/sites-available


  mysql:
    build: config/database
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bernhard
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: internship


  phpmyadmin:
    build: config/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
    ports:
      - 127.0.0.1:8081:80


  php:
    build: config/php
    container_name: php
    volumes:
      - ./config/php:/etc/nginx/sites-available