services:
  app:
    build: config/webserver
    container_name: nginx
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./config/webserver:/etc/nginx/sites-available


  mysql:
    build: config/database
    container_name: mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: bernhard
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: internship


  phpmyadmin:
    build: config/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - 127.0.0.1:8081:80