services:
  app:
    build: .
    image: internship
    ports:
      - 127.0.0.1:8080:80
    working_dir: /planeo_internship
    volumes:
      - ./:/planeo_internship
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: bernhard
      MYSQL_PASSWORD: 12345
      MYSQL_DB: internship


  mysql:
    image: mysql:latest
    volumes:
      - internship-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password1
      MYSQL_DATABASE: internship


volumes:
  internship-mysql-data: